### ISSUE TITLE
issue running tree example

### ISSUE THREAD

**Issue by gesaleh** [matthewelse/bleep#12]
I'm having issue running command command
```
python tree.py 88:0F:10:92:A0:39
Attempting to connect to 88:0F:10:92:A0:39
Traceback (most recent call last):
  File "tree.py", line 36, in <module>
    device.connect()
  File "/usr/local/lib/python2.7/dist-packages/bleep/device.py", line 154, in connect
    self.requester.connect(True, "random")
RuntimeError: Channel or attrib not ready

```

while using pygattlib/example I don't have isseu running the examples
```
/pygattlib/examples# python discover_primary.py  88:0F:10:92:A0:39
Connecting...
{'start': 1, 'end': 11, 'uuid': '00001800-0000-1000-8000-00805f9b34fb'}
{'start': 12, 'end': 15, 'uuid': '00001801-0000-1000-8000-00805f9b34fb'}
{'start': 16, 'end': 24, 'uuid': '0000180a-0000-1000-8000-00805f9b34fb'}
{'start': 25, 'end': 35, 'uuid': '0000181d-0000-1000-8000-00805f9b34fb'}
{'start': 36, 'end': 50, 'uuid': '00001530-0000-3512-2118-0009af100700'}
Done.
```

**Comment by ucoluk** [comment]
Allah başka dert, tasa vermesin. Olur öyle.
