### ISSUE TITLE
TypeError: discover_descriptors() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by staefy** [matthewelse/bleep#15]
I see that a pull request was merged in other repo that was supposed to fix this? Still an issue for me.
What I ran: 

[examples] (master) > python tree.py 732b3078-7c65-4cf3-890d-2390a4ca0221
Attempting to connect to 732b3078-7c65-4cf3-890d-2390a4ca0221
No scheduled event for kCBMsgId53
No scheduled event for kCBMsgId53
Traceback (most recent call last):
  File "tree.py", line 38, in <module>
    device.connect()
  File "/Library/Python/2.7/site-packages/bleep-0.4.4.dev3-py2.7.egg/bleep/device.py", line 172, in connect
    serv = GATTService(self, uuid, start, end)
  File "/Library/Python/2.7/site-packages/bleep-0.4.4.dev3-py2.7.egg/bleep/gatt/service.py", line 55, in __init__
    self._characteristics = self._discover_characteristics()
  File "/Library/Python/2.7/site-packages/bleep-0.4.4.dev3-py2.7.egg/bleep/gatt/service.py", line 78, in _discover_characteristics
    characteristic = GATTCharacteristic(self.device, handle, value_handle, end_handle, BLEUUID(uuid), properties)
  File "/Library/Python/2.7/site-packages/bleep-0.4.4.dev3-py2.7.egg/bleep/gatt/characteristic.py", line 147, in __init__
    self._descriptors = self._discover_descriptors()
  File "/Library/Python/2.7/site-packages/bleep-0.4.4.dev3-py2.7.egg/bleep/gatt/characteristic.py", line 160, in _discover_descriptors
    discovered = self.device.requester.discover_descriptors(self.value_handle + 1, self.end_handle)
TypeError: discover_descriptors() takes exactly 2 arguments (3 given)

**Comment by staefy** [comment]
Fixed by checking out afcd203. Other problem arose.
