### ISSUE TITLE
Dependency: pyxpcconnection

### ISSUE THREAD

**Issue by harshaxnim** [matthewelse/bleep#8]
```
Reading https://pypi.python.org/simple/pyxpcconnection/
Couldn't find index page for 'pyxpcconnection' (maybe misspelled?)
```

I get this error even when I've installed `pyxpcconnection` manually, through `python setup.py install`. What do you think is my problem?

**Comment by harshaxnim** [comment]
I've "resolved" the issue. Might not be very elegant, but hopefully works just without breaking anything.

I installed `pygattosx` and `pyxpcconnection` libraries independently. In `pygattosx`'s setup.py, I've removed the dependency (`pyxpcconnection`) because I know that I've installed it manually.

With this, the installation was successful. The discovery works fine as well, but connect fails with 

```
>>> d[0].connect()
No scheduled event for kCBMsgId53
No scheduled event for kCBMsgId81
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bleep/device.py", line 172, in connect
    serv = GATTService(self, uuid, start, end)
  File "bleep/gatt/service.py", line 55, in __init__
    self._characteristics = self._discover_characteristics()
  File "bleep/gatt/service.py", line 78, in _discover_characteristics
    characteristic = GATTCharacteristic(self.device, handle, value_handle, end_handle, BLEUUID(uuid), properties)
  File "bleep/gatt/characteristic.py", line 147, in __init__
    self._descriptors = self._discover_descriptors()
  File "bleep/gatt/characteristic.py", line 160, in _discover_descriptors
    discovered = self.device.requester.discover_descriptors(self.value_handle + 1, self.end_handle)
TypeError: discover_descriptors() takes exactly 2 arguments (3 given)
```

I'm guessing this has nothing to do with the _jugaad_ that I've done! :P
